---
- name: "install base dependencies"
  package: 
    name: "{{ item }}"
  with_items: "{{ system_dependencies }}"
  become: yes
- name: "install cassandra driver"
  pip: 
    name: "cassandra-driver"
